### ISSUE TITLE
Bing cookie is required

### ISSUE THREAD

**Issue by bt** [rabilrbl/ChatBot-Telegram#1]
Hey there,

I just came across your project and I'd like to try it, but seems like there's been a recent addition of `bing-chat`, which is now causing the Docker to fail if the Bing Cookie is not defined.

I don't have access to Bing Chat, but I'd like to use the Telegram feature for OpenAI via `text-davinci-003`. Would it still be possible to do so?

**Comment by rabilrbl** [comment]
Hi there
I have reverted the changes made with bing AI
As it was causing lot of issues.

I'll be updating this project with newly launched chat gpt api

I have an alternative project going on with python that has both chatgpt and bingai
The project is WIP, it'll be up soon
